// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPgBzL1MTKaXebM-_fZSIRaN2JMQ3zy2U',
    appId: '1:479889339910:android:20c923bd95f0663da4f587',
    messagingSenderId: '479889339910',
    projectId: 'gestao-estoque-50b27',
    storageBucket: 'gestao-estoque-50b27.firebasestorage.app',
  );

  // ✔ Android - Já estava correto no seu projeto.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfSHpv28MggYxIsjDZ3yY2-Ts-dxVHMZY',
    appId: '1:479889339910:web:47b58a5edec03876a4f587',
    messagingSenderId: '479889339910',
    projectId: 'gestao-estoque-50b27',
    authDomain: 'gestao-estoque-50b27.firebaseapp.com',
    storageBucket: 'gestao-estoque-50b27.firebasestorage.app',
  );

  // ⭐ WEB - ESTE É O BLOCO QUE IMPORTA PARA VOCÊ AQUI!

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByqb5vApr7gh20zqTfPra2mpiNxK9b2ws',
    appId: '1:479889339910:ios:138a303abf876c6ba4f587',
    messagingSenderId: '479889339910',
    projectId: 'gestao-estoque-50b27',
    storageBucket: 'gestao-estoque-50b27.firebasestorage.app',
    iosBundleId: 'com.example.gestaoEstoque',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByqb5vApr7gh20zqTfPra2mpiNxK9b2ws',
    appId: '1:479889339910:ios:138a303abf876c6ba4f587',
    messagingSenderId: '479889339910',
    projectId: 'gestao-estoque-50b27',
    storageBucket: 'gestao-estoque-50b27.firebasestorage.app',
    iosBundleId: 'com.example.gestaoEstoque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjHfIC7MyUWsAf-DGHV_IrSiiCmuXRDng',
    appId: '1:479889339910:web:56b7311e7c74a9dda4f587',
    messagingSenderId: '479889339910',
    projectId: 'gestao-estoque-50b27',
    authDomain: 'gestao-estoque-50b27.firebaseapp.com',
    storageBucket: 'gestao-estoque-50b27.firebasestorage.app',
  );

}